version: '3.9'
services:
  postgres-server:    # The Postgres Database Service
    image: postgres:latest
    restart: always
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixmon
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:  # Volumes for scripts and related files you can add
      - ./pgdata:/var/lib/postgresql/data
    networks:
      zabbix-network:
        ipv4_address: 172.18.0.6

  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:alpine-latest
    restart: always
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixmon
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_IPMIPOLLERS: 1
    depends_on:
      - postgres-server
    volumes:  # Volumes for scripts and related files you can add
      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    ports:
      - 10051:10051
    networks:
      zabbix-network:
        ipv4_address: 172.18.0.3

  zabbix-web:    # The main Zabbix web UI or interface
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbixmon
      ZBX_SERVER_HOST: 172.18.0.3  # Zabbix related and Php variables
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Europe/Moscow"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 8081:8080
      - 8443:8443
    networks:
      zabbix-network:
        ipv4_address: 172.18.0.4

  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:latest
    privileged: true   #access mode for allowing resource access
    # network_mode: "host"
    # userns_mode: "host" #Disable namespace remapping for a container
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: 172.18.0.3 #the IP/Dns of Zabbix server
    ports:
      - 10050:10050
    networks:
      zabbix-network:
        ipv4_address: 172.18.0.5

#  adminer:  #Optional for accessing databases
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      zabbix-network:
#        ipv4_address: 172.18.0.7

#  grafana-xxl:  #optional more functional and creative UI
#    image: monitoringartist/grafana-xxl:latest
#    ports:
#     - 3000:3000
#    networks:
#      zabbix-network:
#        ipv4_address: 172.18.0.8

networks:
  zabbix-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
